---
title: "Research"
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = FALSE, #set to false to hide code
               message = FALSE,
               warning = FALSE,
               out.width = "100%",
               dpi = 200,
               fig.align = "center")  
```

<script>
function hide_buttons(abstract) {
  var x = document.getElementById(abstract);
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

## Work in Progress

### An Experimental Perspective on Urban Toll Acceptability

with [Philippe Gagnepain](https://www.parisschoolofeconomics.eu/personnes/philippe-gagnepain/) and [Carine Staropoli](https://www.parisschoolofeconomics.eu/personnes/carine-staropoli/) 

<em> [Draft available upon request] <em> 

<button class="button_link" role="button" onclick="hide_buttons('abstract_toll')">Abstract</button>
<div id="abstract_toll" style="display:none;">

This paper investigates the effectiveness and acceptability of urban tolls as a policy instrument in transport economics to reduce private car use. It focuses on everyday commuting decisions under time constraints and heterogeneous spatial access to public transport infrastructure. We consider an experimental approach to test how commuters adjust their modal choices after road pricing is introduced and when congestion is endogenously formed. We also assess the social acceptability of tolls and the role of distributive fairness in shaping support. We compare alternative pricing structures to explore how differentiated charges affect both modal shift and perceived equity. Our results show that congestion pricing reduces car use and encourages substitution toward public transport when the infrastructure is available. However, public support remains limited among individuals who perceive the scheme as unfair. Our findings thus underscore the importance of integrating efficiency and equity considerations when designing politically feasible urban transport policies. 
</div> 

<br />



### Come Pick-Me Up: Understanding (Non-)Monetary Motives in Carpool Drivers 

<button class="button_link" role="button" onclick="hide_buttons('abstract_carpool')">Abstract</button>

<div id="abstract_carpool" style="display:none;">

How do carpool drivers choose their passengers? This paper investigates both monetary and non-monetary motives on the supply side of peer-to-peer markets. I focus on BlaBlaCar, the world’s largest carpooling platform, where drivers post trips with empty seats and passengers send booking requests. Using detailed observational data, I first document a key platform friction and estimate reduced-form acceptance models. I leverage a specific feature of the platform that allows drivers to make short detours from their originally planned route in order to pick up additional passengers. The evidence shows that drivers are less likely to accept requests that are more costly in terms of detour, timing, or seat scarcity. This suggests that low acceptance is not only a matter of price, but also reflects the private cost of adapting a trip and the strategic value of keeping a seat available. I then develop a dynamic choice model of driver behavior in which drivers may receive several booking requests before departure. The key challenge lies in the imperfectly observed opportunity cost of accepting a request. The model will allow me to estimate the opportunity cost of acceptance and evaluate counterfactual platform policies, including targeted Boost proposals and pricing rules. The project sheds light on how suppliers face hidden, dynamic, and non-monetary costs in peer-to-peer markets.

</div> <br />

### How Much as Changed? The Impact of the Pandemic on Long-Distance Mobility





<br />

### More Trains for Whom? Experimental Evidence on Perceived Rail Frequency Improvements
with <em> SNCF Réseau <em>


<br />



## Other Project

### Truth hurts: the dynamics of motivated mislearning  

with [Luca Cocco](https://sites.google.com/view/lucacocco/overview?authuser=0) and Lidia Esposito  

<br />

