---
title: "Research"
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = FALSE, #set to false to hide code
               message = FALSE,
               warning = FALSE,
               out.width = "100%",
               dpi = 200,
               fig.align = "center")  
```

<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

## Work in Progress

### In Search of Working Time? Hours Constraints, Firms and Mobility

This paper provides novel empirical evidence on hours constraints—barriers for workers to work their preferred hours at a given wage rate—by linking self-reported hour preferences from large-scale survey data with administrative employer-employee data between 2003 and 2023. Exploiting a unique feature of the French Labor Force Survey, I build a unique linkage covering a majority of surveyed workers and discuss new insights on hours constraints. First, I investigate the employment structures that favor the emergence of hours constraints. Involuntary part-time employment is heavily concentrated in specific low-skill jobs that are intensive in part-time work and are associated with limited outside options. Firm sorting is a strong driver of constraints, as constrained workers are disproportionately employed at low-hours and low-wage firms. Second, I leverage the panel dimension of my data to track labor market trajectories of workers who want to increase their hours. Constrained workers are more likely to move across employers but are heterogeneous in their ability to increase their hours and earnings when moving. Using a welfare framework, I identify the workers' willingness to pay to relax their hours constraints. 

<br />

### Child Penalty and Hours Constraints

<button class="button_link" role="button" onclick="hide_buttons('abstract_childpen')">Abstract</button>
<div id="abstract_childpen" style="display:none;">
A large literature has settled the existence of a child penalty, i.e the idea that the arrival of the first child creates a long-run gender gap in earnings. An important source for the child penalty lies in the differential evolution of hours worked across men and women following the birth of the child. In particular, many women tend to transition to part-time work when they have their first child and remain in such positions for a certain number of years. As their children grow up, women may yet be willing to return to their initial full-time working status. An important question concerns whether they are able to do so, reflecting on an important body of research on involuntary part-time work. I combine panel administrative data with survey information on hours constraints to distinguish what share of the child penalty in hours is driven by constraints, as opposed to voluntary part-time work reflecting gender norms or stronger taste for child care.
</div> 

<br />

## Working Papers

### When Workers Don’t Know Their Contract: Evidence from French Working Time Regulations 

with [Thomas Breda](https://www.parisschoolofeconomics.com/breda-thomas/index_en.html) and [Vladimir Pecheu](https://vladimirpecheu.com/) 

<a href="pdf/draft_forfaits.pdf">Paper</a> <span style="color: red; font-size: 1.0em; font-weight: bold; margin-left: 8px;">NEW !!!</span>

<button class="button_link" role="button" onclick="hide_buttons('abstract_forfait')">Abstract</button> 
<div id="abstract_forfait" style="display:none;">
This paper examines workers' awareness of their contractual working time arrangements and its consequences for labor market outcomes. Combining administrative and survey data at the individual level, we construct a new and unique data set which shows that 20% of the workforce mistakenly think that they work under day contracts, with no monitoring of hours, while they are actually paid through a standard hours contract. This reveals that many workers with various profiles do not know the legal environment governing something as fundamental as their working time. We show that these "ignorant" workers differ from classic workers in terms of working conditions: they perform more unpaid overtime hours but have a higher wage rate per contractual hour, so that their total compensation is similar.  Complementary results on job satisfaction also suggest that firms do not take advantage of their workers' ignorance of labor contracts to extract rents. Rather, "ignorant" workers appear to benefit from an intermediate status between standard hours contracts and day contracts with more flexibility. Leveraging the panel dimension of our data, we further show that these workers are more likely to sign actual day contracts over time, but with smaller effects on their earnings' trajectories.
</div> 

<br />

###   Le Développement des Nouveaux Indépendants Est-Il un Facteur de Tension sur le Marché du Travail Salarié ? 

with [Philippe Askenazy](https://cmh.ens.fr/author/philippe-askenazy/) and [Christine Erhel](https://ceet.cnam.fr/le-ceet/chercheur-euse-s/christine-erhel-lirsa-ceet--988265.kjsp), Connaissance de l'Emploi n°203, December 2024.

<a href="pdf/CDE_203_Independants.pdf">Paper</a>

## Policy (in French)

-   [Baisse de la Productivité en France : Echec en « maths » ?](https://www.cae-eco.fr/staticfiles/pdf/cae_Focus091.pdf) (Declining Productivity in France : A "Math" Problem?), Focus du CAE no. 091-2022, September 2022.
-   [Activité Partielle et Situation Pré-Crise des Entreprises](https://www.cae-eco.fr/staticfiles/pdf/cae-focus082.pdf) (Short-Time Work and the Pre-Crisis Situation of Firms), Focus du CAE n°082-2022, March 2022.
-   [Immigration et Difficultés de Recrutement](https://www.cae-eco.fr/staticfiles/pdf/cae-focus073(2).pdf) (Immigration and Recruitment Difficulties), Focus du CAE n°073-2021, November 2021. 